services:
  db:
    image: postgres:34
    environment:
      POSTGRES_USER: mahad
      POSTGRES_PASSWORD: mahad6666
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://b7e69dc967a83ae4dad3c244d7531a6b81cbcacedc6249d5c655b1bc012fc563:sk_3XuMD6r_UQ19pdKd1_BEe@db.prisma.io:5432/postgres?sslmode=require
    depends_on:
      - db